### ISSUE TITLE
Kelowna DC01

### ISSUE THREAD

**Issue by notcat** [notcat/ICT-127-Lab-7#1]
### DC01-Kelowna

Hostname: DC01-Kelowna
IP Address: 10.10.8.1
DNS: 10.10.8.1, 10.10.8.2, 10.10.12.1, 10.10.12.2, 

Features: 
- AD DS
- DNS
- DHCP
- DFS Namespaces
- DFS Replication

DHCP Scope: 
Users
- 10.10.8.51 - 10.10.10.255

### Tasks

- [ ] Configure hostname, IP address and firewall
- [ ] Install the features
- [ ] Promote DC01-Kelowna to a domain controller
- [ ] Configure DNS and create Reverse Lookup Zone
- [ ] Create DHCP Scope
- [ ] Configure DFS Namespaces
- [ ] Configure DFS Replication
- [ ] Format a hard drive
- [ ] Create Organization Unit
- [ ] Create users
- [ ] Create map driving policies
- [ ] Create a folders used for DFS and map driving

### Verification
- [ ] Verify the IPv4 Address, sub netmask, default gateway, DNS servers, hostname and Firewall (ping allowed)
- [ ] Verify AD DS, DNS, DHCP and DFS are installed
- [ ] Verify DC01 is Main domain controller
- [ ] Verify reversed lookup is properly configured
- [ ] Verify that DHCP is working and able to connect a staff PC
- [ ] Verify DFS namespaces and replication
- [ ] Verify if you can access the hard drive and folders on it
- [ ] Verify Organizational unit and users
- [ ] Verify map driving policies

### Notes

For verification of DNS use NS lookup.
For verification of map driving when user login they can access the drive and wont able to access drives that they are restircted.
