### ISSUE TITLE
Kelowna DC02

### ISSUE THREAD

**Issue by notcat** [notcat/ICT-127-Lab-7#2]
### DC02-Kelowna

Hostname: DC02-Kelowna
IP Address: 10.10.8.2
DNS: 10.10.8.1, 10.10.8.2, 10.10.12.1, 10.10.12.2, 

Features: 
- AD DS
- DNS
- DHCP
- DFS Namespaces
- DFS Replication

DHCP Failover:
- 50-50 scope balance

### Tasks

- [ ] Configure hostname, IP address, and DNS
- [ ] Install the features
- [ ] Join the int.raudz.com domain
- [ ] Go back to DC01-Kelowna and configure this as a DHCP failover server (50-50 balance)
